site_name: Datenizen Meta
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences

nav:
  - Documentation: index.md